### ISSUE TITLE
Minor typo in headline

### ISSUE THREAD

**Issue by RayRoestenburg** [orrsella/sbt-sublime#18]
In the repo headline:

An sbt pluign for generating Sublime Text projects with library dependencies sources

(pluign -> plugin)

Thanks for a great plugin BTW have been using it for years :-)

**Comment by orrsella** [comment]
Whoa, amazing that I never saw it! Fixed.

Thanks! Glad you're a happy user :)

**Comment by RayRoestenburg** [comment]
👍
