### ISSUE TITLE
Please release a version compatible with SBT 1.0

### ISSUE THREAD

**Issue by agemooij** [orrsella/sbt-sublime#19]
This plugin is one of the last ones on my list of essential plugins before I can move all our projects to SBT 1.0. It would be great if you could release a version built against Scala 2.12 and SBT 1.0.

**Comment by orrsella** [comment]
Hey, I want to do this, but just haven't gotten around to it. Will try to in next weekend.

**Comment by orrsella** [comment]
I'm fallen a bit out of touch with the Scala ecosystem. Have you done this recently for other plugins? Any hoops I'll need to jump thru in order to get this working from sbt 0.13?

**Comment by agemooij** [comment]
I have done this for two of my own plugins so far and it varied from minor tweaks to add support for cross-building to dealing with some code changes for deprecated or removed API.

I had a quick look at the build file for sbt-sublime and it seems to still support SBT 0.12 and Scala 2.9. would you be OK with removing that to simplify things a little bit?

**Comment by agemooij** [comment]
Based on a quick look at the build file and source code I don't see any potential problems so I can try to hack something together as a starting point this week.

**Comment by orrsella** [comment]
I released version `1.1.2` which should work for sbt 1.0. Please give it a try and let me know if you have any issues. Thanks!

**Comment by agemooij** [comment]
@orrsella Awesome, thanks! 

I tested it successfully. I also updated the plugin status on the [SBT 1.0 migration wiki](https://github.com/sbt/sbt/wiki/sbt-1.x-plugin-migration) so other users are aware of the release.

I noticed that the README still says that you should use 1.1.1 for SBT 0.13.x but since you have cross-released the latest version, that should not be necessary. Both user groups should be able to use 1.1.2 now.

Thanks again!

**Comment by agemooij** [comment]
@orrsella  I just ran into the problem of 1.1.2 not having been cross-released but released only for SBT 1.0. 

This makes it impossible for me to run sbt-sublime on multiple projects, some of which have already transitioned to 1.0 but some of which are not under my control and still run 0.13. It forces me to keep separate plugin configurations for both SBT versions (I have 0.13 symlinked to 1.0 at the moment).

Any chance you could release 1.1.2 for 0.13 too? It should be completely seamless to do so.

**Comment by orrsella** [comment]
Sure, I actually ran into some problems trying to cross release so only released for 1.0.

I used: `sbt> release cross with-defaults` but it only released for the version of sbt I was running.

Any idea what I'm doing wrong?

**Comment by agemooij** [comment]
It should just be `^ publish` for a full cross release or, f you want to release a specific version, switch to correct SBT version using `^^ 0.13.16` and then do a normal `publish`.

I'm not sure how the release plugin interacts with this though.

**Comment by agemooij** [comment]
These were the (minimal) docs I used: http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt-cross-building

**Comment by orrsella** [comment]
That's what I did — switched to `0.13.16`. Version `1.1.2` for 0.13 should be in maven central soon (it's already [in sonatype](https://oss.sonatype.org/content/repositories/releases/com/orrsella/sbt-sublime_2.10_0.13/1.1.2/)).

**Comment by agemooij** [comment]
Awesome, thanks!
